### PR TITLE
Add Nucleo F446ZE port to FreeRTOS_apps

### PR DESCRIPTION
**Pull request by alsaibie**
A port similar to the Olimex FreeRTOS example but for the Nucleo F446 board.
The project structure is the same, except:
- the FreeRTOS-POSIX plugin is moved to a lib folder.
- the serial_transport.h/.c files are moved in a separate folder to highlight that their excluded from the firmware build and are only copied over to XCRE 
Recommended change: move the arm toolchain installation outside of the firmware folder, or have it as a prequisite since it is used by most boards.

### CODE REVIEW

**Comment by ralph-lange** [comment]
Very nice contribution. Thank you very much, @alsaibie. This will take a bit longer to review. I'll ask @pablogs9 for that.

**Comment by alsaibie** [comment]
You're most welcome. I have a nucleo F3 and L4, would you care to have them ported as well? Or having a porting guide under README.md would do, since other Nucleo board setups are very much the same?

Will wait for the review first.

**Comment by pablogs9** [comment]
@ralph-lange It looks good to me, but we don't have any Nucleo F446ZE here for test... do you have any? If not I proposed to merge this PR since it only modifies a F446ZE-related folder. 

Once merged, we have to check this other PR: https://github.com/micro-ROS/micro-ros-build/pull/139

**Comment by ralph-lange** [comment]
> @ralph-lange It looks good to me, but we don't have any Nucleo F446ZE here for test... do you have any? If not I propose to merge this PR since it only modifies a F446ZE-related folder.
I have none either, but I agree to merge.

**Pull request merged**
